### ISSUE TITLE
Non consistent case in filenames for imageio_interface.jl (or ImageIO_interface.jl)

### ISSUE THREAD

**Issue by AlainLich** [JuliaIO/ImageMagick.jl#1]
Hi,

in https://github.com/JuliaIO/ImageMagick.jl/blob/master/src/ImageMagick.jl, one reads (line 11):
`@lazymod ImageMagickIO "imageio_interface.jl"`
whereas the file name has upper case characters:  `ImageIO_interface.jl`.
On systems( or filesystems) where case is significant (incl. my Linux ),this is an issue.
Can be corrected either ways.

**Comment by SimonDanisch** [comment]
Ah snap, i correctes this on my linux machine, but obviously didn't commit the fix... Thank you!

**Comment by SimonDanisch** [comment]
Lets go for imageio_interface.jl ....This is closer to the naming convention i losely stick to lately

**Comment by SimonDanisch** [comment]
should be fixed!

**Comment by AlainLich** [comment]
Hi
just reloaded  ImageMagick,
getting a weird diagnostics:

```
ERROR: LoadError: LoadError: LoadError: ImageMagick not properly installed. Please run Pkg.build("ImageMagick") then restart Julia.
 in error at error.jl:21
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in #319#includehere at /home/alain/.julia/v0.4/Requires/src/lazymod.jl:16
 in imagemagickio at /home/alain/.julia/v0.4/Requires/src/lazymod.jl:17
 in visualize at /home/alain/.julia/v0.4/GLVisualize/src/visualize_interface.jl:20 (repeats 2 times)
 in anonymous at no file:169
 in _treeWalkPre! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:257
 in _treeWalkPre! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:268 (repeats 2 times)
 in treeWalk! at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/SubScreens.jl:233 (repeats 2 times)
 in init_romeo at /home/alain/.julia/v0.4/Romeo/src/XMLScreens/RomeoLib.jl:240
 in realMain at /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl:119
 in main at /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl:209
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:134
 in process_options at ./client.jl:310
 in _start at ./client.jl:409
while loading /home/alain/.julia/v0.4/ImageMagick/src/libmagickwand.jl, in expression starting on line 10
while loading /home/alain/.julia/v0.4/ImageMagick/src/imageio_interface.jl, in expression starting on line 6
while loading /home/alain/src/Julia/Romeo.jl/test/RomeoMain.jl, in expression starting on line 212

```

**Comment by SimonDanisch** [comment]
Did you try building it?

**Comment by AlainLich** [comment]
Just did it,  this solves the problem.

**Comment by AlainLich** [comment]
Just pushed in branch XML, my next step is likely to test ColorChooser and possibly edit. 
Let me know if you have a preference for doc format, I will need to write some explanation on how the XML works ( I think adding a doc directory). (Some of the XML is obvious, referring to functions in code  deserves some explanation; then I will have to test what I will say.)
Best 
Alain

**Comment by SimonDanisch** [comment]
I don't really have any preference... You're doing already 10x more documentations than I do :)
