### ISSUE TITLE
Build.jl installs the wrong package on Arch Linux

### ISSUE THREAD

**Issue by robbystk** [JuliaIO/ImageMagick.jl#118]
ImageMagick requires the file /usr/lib/libMagickWand-6*.so which is in the package `libmagick6` on Arch, but the `imagemagick` package gets installed which currently installs `libmagick` version 7 (as a dependency), which ImageMagick is incompatible with.  
PR incoming.

**Comment by robbystk** [comment]
Thanks for merging!

**Comment by musm** [comment]
thank you for the fix!
