### ISSUE TITLE
init_deps not found when imagemagick is already installed on OSX

### ISSUE THREAD

**Issue by rened** [JuliaIO/ImageMagick.jl#12]
Using 0.4 and the currently tagged versions of Images and ImageMagick I get the following error at `using ImageMagick`.

``` jl
WARNING: Method definition writemime(Base.IO, Base.Multimedia.MIME{:image/png}, Images.AbstractImage) in module Images at /Users/rene/.julia/v0.4/Images/src/io.jl:216 overwritten in module ImageMagick at /Users/rene/.julia/v0.4/ImageMagick/src/ImageMagick.jl:276.
WARNING: Method definition writemime(Array, Base.IO, Base.Multimedia.MIME{:image/png}, Images.AbstractImage) in module Images overwritten in module ImageMagick.
WARNING: Method definition writemime(Base.IO, Base.Multimedia.MIME{:image/png}, Images.AbstractImage) in module Images at /Users/rene/.julia/v0.4/Images/src/io.jl:216 overwritten in module ImageMagick at /Users/rene/.julia/v0.4/ImageMagick/src/ImageMagick.jl:276.
WARNING: Method definition writemime(Array, Base.IO, Base.Multimedia.MIME{:image/png}, Images.AbstractImage) in module Images overwritten in module ImageMagick.
ERROR: LoadError: InitError: UndefVarError: init_deps not defined
 in __init__ at /Users/rene/.julia/v0.4/ImageMagick/src/libmagickwand.jl:38
 in _require_from_serialized at loading.jl:84
 in require at ./loading.jl:251
```

The same happens when using the latest checkouts of both packages.

Note that in both cases I have the imagemagick library already installed through "brew install imagemagick", i.e. outside of Julia.

When I uninstall the package from my homebrew installation and run `Pkg.build("ImageMagick")`, Homebrew.jl installes the dependencies and from then on Images and ImageMagick work.

**Comment by SimonDanisch** [comment]
`init_deps` is missing because of the issue, that BinDeps doesn't include the load hooks when the library is already present.
@staticfloat, was there a solution for this?
`ImageMagick` doesn't go with the currently tagged `Images` version, if I haven't missed anything ;)
We should have resolved the last issues and @timholy wanted to go tagging after this is resolved:
 JeffBezanson/FixedPointNumbers.jl#27

**Comment by staticfloat** [comment]
The Homebrew hook will not be run if the binaries aren't coming from `Homebrew.jl` (which is the case when you already have binaries available on your system).

I believe to have a `preload` hook for `SystemPaths`-satisfied binaries, we are going to need to find some way to attach those `preload` hooks to the `SystemPaths` provider via BinDeps.  @keno do you think this is possible via something like `provides( SystemPaths, "libwand", preload = ... )`?

**Comment by tbreloff** [comment]
I also see this issue on Centos 7 with system installed ImageMagick.  Is there a short-term fix?

**Comment by SimonDanisch** [comment]
Can you post the contents of Images/deps/deps.jl?

**Comment by tbreloff** [comment]
Error:

```
ERROR: LoadError: InitError: UndefVarError: init_deps not defined
 in __init__ at /home/tom/.julia/v0.4/ImageMagick/src/libmagickwand.jl:38
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
during initialization of module ImageMagick
while loading /home/tom/.julia/v0.4/Plots/test/imgcomp.jl, in expression starting on line 20
```

deps.jl:

```
[tom@tomoffice Plots]$ cat ../Images/deps/deps.jl 
# This is an auto-generated file; do not edit

# Pre-hooks

# Macro to load a library
macro checked_lib(libname, path)
    ((VERSION >= v"0.4.0-dev+3844" ? Base.Libdl.dlopen_e : Base.dlopen_e)(path) == C_NULL) && error("Unable to load \n\n$libname ($path)\n\nPlease re-run Pkg.build(package), and restart Julia.")
    quote const $(esc(libname)) = $path end
end

# Load dependencies
@checked_lib libwand "/lib64/libMagickWand.so.5"

# Load-hooks
```

**Comment by SimonDanisch** [comment]
thanks! So it does actually have the correct path in there.
I guess I don't really understand the purpose of the hooks and why they're missing in that case.
Maybe we should just stop using the hooks and move them into ImageMagick, since the path is all we need.
You should be able to temporarily fix this by putting this into deps.jl:

``` Julia
function init_deps()
    ccall((:MagickWandGenesis,libwand), Void, ())
end
```

**Comment by tbreloff** [comment]
I'll probably need to wait for a real fix, as I want to use it for doing integration testing on travis.  See: https://github.com/tbreloff/Plots.jl/issues/38.  Though I suppose I could fork, make the change, and point travis to the fork...

**Comment by vchuravy** [comment]
I am running into this too on a Centos machine...

```
julia> BinDeps.debug("ImageMagick")
INFO: Reading build script...
The package declares 1 dependencies.
 - Library "libwand"
    - Satisfied by:
      - System Paths at /usr/lib64/libMagickWand.so.2
    - Providers:
      - BinDeps.AptGet package libmagickwand4 (can't provide)
      - BinDeps.AptGet package libmagickwand5 (can't provide)
      - BinDeps.AptGet package libmagickwand-6.q16-2 (can't provide)
      - BinDeps.Pacman package imagemagick (can't provide)
      - BinDeps.Yum package ImageMagick
```

resulting deps.jl file

```
# This is an auto-generated file; do not edit

# Pre-hooks

# Macro to load a library
macro checked_lib(libname, path)
    ((VERSION >= v"0.4.0-dev+3844" ? Base.Libdl.dlopen_e : Base.dlopen_e)(path) == C_NULL) && error("Unable to load \n\n$libname ($path)\n\nPlease re-run Pkg.build(package), and restart Julia.")
    quote const $(esc(libname)) = $path end
end

# Load dependencies
@checked_lib libwand "/usr/lib64/libMagickWand.so.2"

# Load-hooks

```

**Comment by timholy** [comment]
If someone is watching and wants to quickly test #14, that would be great. But if CI passes I'll merge and tag (hopefully in a few minutes), since it's not good to have the `UFixed` incompatibility around any longer than necessary.

**Comment by oschulz** [comment]
This has just resurfaced (at least on CentOS-7 with system installed ImageMagic), as 286138d removed the fix.

See #91.
