### ISSUE TITLE
ImageMagick overrides existing executables in PATH

### ISSUE THREAD

**Issue by anthony-wang** [JuliaIO/ImageMagick.jl#120]
Platform: Win10, Julia v0.6.2, ImageMagick v0.5.1

When `using ImageMagick`, it overrides existing bindings in PATH and does it silently. This can cause unexpected behaviour when the binary from `ImageMagick` and the originally existing binary from PATH are not the same.

```
julia> run(`where ffmpeg`)
C:\ProgramData\chocolatey\bin\ffmpeg.exe

julia> run(`ffmpeg -version`)
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers

julia> using ImageMagick

julia> run(`where ffmpeg`)
C:\Users\Anthony\.julia\v0.6\ImageMagick\deps\usr\lib\x64\{app}\ffmpeg.exe
C:\ProgramData\chocolatey\bin\ffmpeg.exe

julia> run(`ffmpeg -version`)
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
```

Thanks to @SimonDanisch for helping debug this!

**Comment by SimonDanisch** [comment]
Should be fixed by #121!
