### ISSUE TITLE
Dependency on Images.jl is too much?

### ISSUE THREAD

**Issue by juliohm** [JuliaIO/ImageMagick.jl#127]
Hello,

I am trying to port packages to Julia v0.7, which depend on loading images from disk (e.g. VisualRegressionTests.jl) and realized that ImageMagick.jl currently depends on the whole Images.jl project. Is there any way to shrink this dependency to something more manageable? Someone familiar with the code can point what parts of the project are being used?

Thank you,

**Comment by SimonDanisch** [comment]
See: https://github.com/JuliaIO/ImageMagick.jl/pull/125

**Comment by juliohm** [comment]
Nice, this one can be closed, it is fixed.
