### ISSUE TITLE
Building on Windows fails because of symlinks in libz and libpng

### ISSUE THREAD

**Issue by krcools** [JuliaIO/ImageMagick.jl#131]
Like a number of other packages, ImageMagick cannot be build on Windows as a limited user because the downloads for libz and libpng contain symlinks. This gives a "Access is denied" error on unpacking.

In the case of libz, a new binary was released to fix this. It also seems some work was done for libpng. Could ImageMagick be updated to use these newly prepared binaries?

Apologies if this is already fixed. I tried the master branch to install.

**Comment by SimonDanisch** [comment]
Yes, I was working on it - but somehow the binarybuilder/provider packages are in shift right now and I couldn't get the travis script to work.
Feel free to have a look at https://travis-ci.org/search/libpngbuilder ! If we get those going we should be able to fix this quickly!

**Comment by krcools** [comment]
It looks like things would be solved with a new release of BinaryBuilder. At version 0.0.4 it is not including version numbers in calls to `BinaryProvider.package`, as is required in the latest release of `BinaryProvider`.

**Comment by krcools** [comment]
I have created a [PR](https://github.com/SimonDanisch/LibpngBuilder/pull/1) on libpngbuilder where as a temporary fix the latest BinaryBuilder is checked out.
