### ISSUE TITLE
/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found 

### ISSUE THREAD

**Issue by gzhang8** [JuliaIO/ImageMagick.jl#140]
I get this error when loading an image. This runs fine a day before but not now. I didn't add any thing into my system PATH. Any idea why this happened? Is there a solution other than compiling and installing a newer version of zlib? Thanks.
```
InitError: error compiling __init__: could not load library "~/.julia/packages/ImageMagick/d5KBL/deps/usr/lib/libMagickWand-6.Q16.so"
/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by ~/.julia/packages/ImageMagick/d5KBL/deps/usr/lib/libpng16.so.16)
during initialization of module ImageMagick
```

**Comment by RalphAS** [comment]
Some other package has linked to the version of `libz` provided by your operating system; Gtk.jl is an example of such a package. ImageMagick needs a newer version, such as the one it installs (but that is not used if the other one is loaded first.) 
For now, the solution is to execute `import ImageMagick` before using the other package.

**Comment by gzhang8** [comment]
@RalphAS Thanks. Works great with import

**Comment by xiuliren** [comment]
any other solutions? what if I have to use the other version of libz first?

**Comment by timholy** [comment]
Consider adding `using ImageMagick` to your `~/.julia/config/startup.jl` file.

In the longer term I am thinking we may have to migrate away from Gtk in ImageView and other applications, if this issue isn't fixed.

**Comment by xiuliren** [comment]
should we reopen this issue? The temporal solution of startup.jl is not really a solution for large software deployment.
