### ISSUE TITLE
Unsatisfiable requirements detected for package CUDAnative [be33ccc6]:

### ISSUE THREAD

**Issue by lannisite110** [JuliaIO/ImageMagick.jl#143]
(v1.0) pkg> add ImageMagick
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CUDAnative [be33ccc6]:
 CUDAnative [be33ccc6] log:
 ├─possible versions are: [0.1.0-0.1.3, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.2, 0.5.0-0.5.5, 0.6.0-0.6.3, 0.7.0, 0.8.0-0.8.10, 0.9.0-0.9.1, 0.10.0-0.10.1] or uninstalled
 ├─restricted to versions * by CuArrays [3a865a2d], leaving only versions [0.1.0-0.1.3, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.2, 0.5.0-0.5.5, 0.6.0-0.6.3, 0.7.0, 0.8.0-0.8.10, 0.9.0-0.9.1, 0.10.0-0.10.1]
 │ └─CuArrays [3a865a2d] log:
 │   ├─possible versions are: 0.8.1 or uninstalled
 │   └─CuArrays [3a865a2d] is fixed to version 0.8.1+
 └─restricted by compatibility requirements with CUDAdrv [c5f51814] to versions: uninstalled — no versions left
   └─CUDAdrv [c5f51814] log:
     ├─possible versions are: 1.0.0 or uninstalled
     └─CUDAdrv [c5f51814] is fixed to version 1.0.0+

**Comment by timholy** [comment]
This is not an ImageMagick bug; you could have picked any new package and gotten the same error. Presumably `pkg> resolve` shows the same error.

It seems you have some inconsistency in your CUDAnative, CuArrays, and/or CUDAdrv packages. Check their status to figure out the problem.
