### ISSUE TITLE
0.7.2 not registered in General registries

### ISSUE THREAD

**Issue by Petr-Hlavenka** [JuliaIO/ImageMagick.jl#148]
The 0.7.2 version is tagged (since Oct 29, 2018 by @musm) but has not been propagated into general registries by attobot. Does anyone know what is the problem?

**Comment by ararslan** [comment]
@JuliaRegistrator `register()`

**Comment by IanButterworth** [comment]
Can a `JuliaIO` org owner `@JuliaRegistrator register()` on [this commit](https://github.com/JuliaIO/ImageMagick.jl/commit/3c4e1c107d6c22f090c8302b5a83da406008c580) to get the old v0.7.2 registered and resolve this issue? Thanks

**Comment by timholy** [comment]
Now that we have 0.7.3, do we actually need 0.7.2? Meaning, would releasing 0.7.2 solve an actual problem?

**Comment by IanButterworth** [comment]
I guess not. I just thought it would look odd in the registry to have a version that's tagged on github missing during the resolve process, if there are `Unsatisfiable requirements` errors. I defer to your judgement @timholy

**Comment by timholy** [comment]
Minutes are precious, so I'll skip :wink:

**Comment by IanButterworth** [comment]
Closed as 0.7.3 has been released
