### ISSUE TITLE
Application crashing when corrupt image is decoded, can't try-catch

### ISSUE THREAD

**Issue by nlw0** [JuliaIO/ImageMagick.jl#182]
I'm writing a Gtk app where png images get decoded by ImageMagick.jl. Sometimes I hit a corrupt file, and this ends up triggering these lines
https://github.com/JuliaIO/ImageMagick.jl/blob/39cf88a16b8e88a4ec6455360540e3f97749b577/src/libmagickwand.jl#L187
https://github.com/JuliaIO/ImageMagick.jl/blob/39cf88a16b8e88a4ec6455360540e3f97749b577/src/libmagickwand.jl#L286

Right now this ends up making my application crash. I would like to try-catch here and recover, if possible. Are there any changes that would be necessary in the library, or am I doing something wrong?

**Comment by timholy** [comment]
The title here says, "can't `try/catch`, but I don't understand why that doesn't work. Are you calling this from a Gtk callback? Do you need a `@guarded`? Does it work if you try to load one of the busted files from the REPL rather than your Gtk application?

**Comment by nlw0** [comment]
It's hard for me to reproduce this now, sorry I guess I was fishing for a bug. try-catching load_ works fine in the REPL, I guess if there was any issues it's in my code.
