### ISSUE TITLE
Add support for OpenEXR.

### ISSUE THREAD

**Issue by twadleigh** [JuliaIO/ImageMagick.jl#203]

**Comment by johnnychen94** [comment]
I don't know the details of OpenEXR so I'm afraid there's anything I can help with here. There's an [OpenEXR_jll](https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl) so you could start with an [OpenEXR.jl] package, then register it to ImageIO and FileIO when it works.

[PNGFiles.jl](https://github.com/JuliaIO/PNGFiles.jl) is a good example for this image io wrapper library.

**Comment by twadleigh** [comment]
Thanks for the offer. I created this task just as a placeholder for work I'm doing to make this happen. I created the OpenEXR build recipe behind [OpenEXR_jll](https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl) last night, and I'm currently trying to tweak the build recipe for [ImageMagick_jll](https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl) to link it in without complaint. Lastly will be making any patches here to close the loop.

**Comment by johnnychen94** [comment]
Great to know that! If you need to host OpenEXR.jl under JuliaIO (as ImageIO and PNGFiles do) and let us image people to co-maintain it, please ask without any hesitation.

**Comment by twadleigh** [comment]
It is looking difficult to get [ImageMagick_jll](https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl) built with support for `OpenEXR`. I'm currently in the process of writing a small standalone julia package that wraps the C interface in a FileIO-compatible way. Since it doesn't look like the functionality will be exposed via ImageMagick, I'm closing this.
