### ISSUE TITLE
Add libpng to deps/build.jl

### ISSUE THREAD

**Issue by sglyon** [JuliaIO/ImageMagick.jl#21]
I'm trying to use ImageMagick for a project and have come across some scenarios where without other packages like Cairo installed, ImageMagick can't even load a png. I believe that if we add libpng as a dependency, this issue will be resolved.

I'm happy to work on that (I will mostly copy bits of Cairo's build.jl), but wanted to get a thumbs up from the maintainers here before doing that

**Comment by SimonDanisch** [comment]
Should be fixed by #121!
