### ISSUE TITLE
 [Bug] Loading .tif image produces image artifact

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaIO/ImageMagick.jl#211]
This issue arises from the discussion at [Images.jl issue 1017](https://github.com/JuliaImages/Images.jl/issues/1017).

Essentially, it was concluded that this package has a bug, causing an artifact to be produced when [this](https://drive.google.com/file/d/1dIhkYY5C7EumgCZaLI0TqPlorRjL1BX0/view?usp=sharing) .tiff image was loaded. There was no method for loading it in Images.jl, meaning that the fallback is this package.

I will not take the time to reproduce the issue with only ImageMagick.jl, so if someone would do that, we could close [the original issue (1017 from Images.jl)](https://github.com/JuliaImages/Images.jl/issues/1017.).

**Comment by KronosTheLate** [comment]
Friendly bump

**Comment by ViralBShah** [comment]
The upstream bug is closed. Should this be closed?

**Comment by KronosTheLate** [comment]
The issue is fixed over at TiffImages, which Images.jl now defaults to (I think). When using ImageMagick directly, both the standalong program and this JL package, the image is loaded without this artifact. In other words, I am unable to reproduce this bug when using
- ImageMagick directly
- ImageMagic.jl
- Images.jl
- TiffImages.jl

So it would seem the issue is resolved completely, despite the only relevant change that I know of being that TiffImages.jl started supporting LZW compressed tiff-images. But I can accept an automagical fix, and will therefore close this.
