### ISSUE TITLE
Unable to compile due to BinaryProvider failed install

### ISSUE THREAD

**Issue by tanged123** [JuliaIO/ImageMagick.jl#222]
ImageMagick fails to install now on Julia 1.9 due to upstream issue: https://github.com/JuliaPackaging/BinaryProvider.jl/issues/211

**Comment by xinkai-zhou** [comment]
The same happened to me. Were you able to resolve it? @tanged123

**Comment by ViralBShah** [comment]
It is probably pulling in a very old version if it is pulling BinaryProvider. Works fine for me.
