### ISSUE TITLE
building issues on Windows

### ISSUE THREAD

**Issue by ghost** [JuliaIO/ImageMagick.jl#26]
LoadError: automatic download failed (error 2147942405)

on Julia 0.4.3, Windows 7.
Pkg.build doesnt solve the problem either.

**Comment by ChrisRackauckas** [comment]
It used to throw this error, but it has been working for me now. Try it on latest master?

**Comment by Allardvm** [comment]
Did https://github.com/JuliaIO/ImageMagick.jl/commit/b0bc710b36608ec5c759f6babe9252794a5e3348 fix this?

**Comment by SimonDanisch** [comment]
Should be fixed by #121! Please try again on master!
