### ISSUE TITLE
installation fails on linux

### ISSUE THREAD

**Issue by my-little-repository** [JuliaIO/ImageMagick.jl#37]
I recently reinstalled julia v0.4.5 from the linux generic binary and then installed the Images library, which went fine. I then tried to load a png image at the repl, and got asked to install the imagemagick julia library. Note that imagemagick is installed on my system.

```
julia> myimage = load("/someimage.png")
WARNING: FileIO.NotInstalledError(:ImageMagick,"")
 in checked_import at ~/.julia/v0.4/FileIO/src/loadsave.jl:12
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:79
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:42
Library ImageMagick is not installed but can load format: FileIO.File{FileIO.DataFormat{:PNG}}    ("/someimage.png")
should we install ImageMagick for you? (y/n):
```

I answered yes. Trying once more to load the image gave me the following error.

```
[...]
INFO: Recompiling stale cache file ~/.julia/lib/v0.4/ImageMagick.ji for module ImageMagick.
WARNING: Module Images uuid did not match cache file
  This is likely because module Images does not support  precompilation but is imported by a module that does.
WARNING: ErrorException("__precompile__(true) but require failed to create a precompiled cache file")
 in require at ./loading.jl:268
 in checked_import at ~/.julia/v0.4/FileIO/src/loadsave.jl:13
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:79
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:42 
ERROR: __precompile__(true) but require failed to create a precompiled cache file
 in require at ./loading.jl:268
 in checked_import at ~/.julia/v0.4/FileIO/src/loadsave.jl:13
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:79
 in load at ~/.julia/v0.4/FileIO/src/loadsave.jl:42
```

I tried to reinstall the imagemagick package without success. Here are the versions on my system.
ImageMagick  0.1.4, ImageView 0.1.19, Images 0.5.3., julia version 0.4.5 (2016-03-18 00:58 UTC) 
Official http://julialang.org/ release x86_64-unknown-linux-gnu

**Comment by SimonDanisch** [comment]
Did you ever try this two times? I know this error, and it's usually a problem with precompilation, which goes away when restarting julia and trying it again.

**Comment by my-little-repository** [comment]
Yes. Three times. Same error. Wait, let me try to restart julia.

**Comment by SimonDanisch** [comment]
I mean only:

```
using Images
load(img)
exit()
```

Not installing!

**Comment by my-little-repository** [comment]
Ah. I restarted julia and then loading the image worked. Thanks for the help!
