### ISSUE TITLE
Finding custom libMagickWand.so

### ISSUE THREAD

**Issue by mbrookhart** [JuliaIO/ImageMagick.jl#44]
Hi,

I'm trying to install some Julia packages on a Suse Enterprise 11 cluster that I don't have root access to.  The cluster mangers have installed a lot of modern packages in a non-standard location, and Pkg.build("ImageMagick") is failing because it can't find libMagickWand.so

I've got a copy of libMagickWand-6.Q16.so.2 in an opt directory, is it possible to force the build package to use that library?

Thank you

**Comment by timholy** [comment]
I think you can set the MAGICK_HOME environment variable. Let us know if that works.

**Comment by mbrookhart** [comment]
No luck. I tried pointing at the ImageMagick/lib directory and the so file directly.

**Comment by timholy** [comment]
What's the contents of `deps/deps.jl`? Here's mine:

``` jl
$ cat deps.jl 
# This is an auto-generated file; do not edit

# Pre-hooks

# Macro to load a library
macro checked_lib(libname, path)
    ((VERSION >= v"0.4.0-dev+3844" ? Base.Libdl.dlopen_e : Base.dlopen_e)(path) == C_NULL) && error("Unable to load \n\n$libname ($path)\n\nPlease re-run Pkg.build(package), and restart Julia.")
    quote const $(esc(libname)) = $path end
end

# Load dependencies
@checked_lib libwand "/usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.2"

# Load-hooks
function init_deps()
    ccall((:MagickWandGenesis,libwand), Void, ())
end
```

In particular, `libwand` had better point to your installation.

I haven't looked in detail, but perhaps you have to set `MAGICK_HOME` and then call `Pkg.build("ImageMagick")`.

**Comment by mbrookhart** [comment]
Thanks Tim.  

The deps.jl file isn't getting created.  When I set the MAGICK_HOME = /path/to/libMagickWand-6.Q16.so.2 and then run build, I get (with paths omitted from a work environment):

julia>Pkg.build("ImageMagick")
INFO: Building Rmath
INFO: Building ImageMagick
W: Unable to locate package libmagickwand4
W: Unable to locate package libmagickwand5
W: Unable to locate package libmagickwand-6.q16-2
W: Unable to locate package libmagickwand4
W: Unable to locate package libmagickwand5
W: Unable to locate package libmagickwand-6.q16-2
=============================[ ERROR: ImageMagick ]=============================

LoadError: None of the selected providers can install dependency libwand.
Use BinDeps.debug(package_name) to see available providers

while loading *, in expression starting on line 98

# 

===================================[ BUILD ERRORS ]===================================

WARNING: ImageMagick had build errors.
- packages with build errors remain installed in *
- build the package(s) and all dependencies with `Pkg.build("ImageMagick")`
- build a single package by running its `deps/build.jl` script

#

**Comment by mbrookhart** [comment]
I also tried export MAGICK_HOME = /path/to/ImageMagick/lib/ and export MAGICK_HOME = /path/to/ImageMagick/ with the same error message.

**Comment by timholy** [comment]
Try putting a debugging `@show mpath` [between these two lines](https://github.com/JuliaIO/ImageMagick.jl/blob/e72d4eb8b8d1808701f9514dd602fc6135e045f8/deps/build.jl#L23-L24) just to make sure it's being set properly.

**Comment by mbrookhart** [comment]
That prints the path to my lib folder when I run it.  It seems that provides isn't finding the library there.  I'm not terribly familiar with the inner workings of BinDeps, is it possible to trace that function/run a verbose mode?

**Comment by timholy** [comment]
Dunno. I fix BinDeps bugs so rarely, I don't remember anything and have to start from scratch each time.

**Comment by mbrookhart** [comment]
I might take a break from trying to solve this for a while and try again when 0.5 comes out.

**Comment by mbrookhart** [comment]
Still can't get this to work with v0.5. Despite mpath being correct, and libMagickWand-6.Q16.so existing in the mpath, the line
     provides(Binaries, mpath, libwand)
doesn't find the library. I'll escalate to BinDeps.

**Comment by xiuliren** [comment]
I got the same error with julia-0.6

**Comment by mbrookhart** [comment]
Looks like it's a bug in [BinDeps](https://github.com/JuliaLang/BinDeps.jl/issues/246#issuecomment-250316758)

**Comment by mbrookhart** [comment]
Closing, stale, haven't revisited.
