### ISSUE TITLE
UInt16 TIFF

### ISSUE THREAD

**Issue by bjarthur** [JuliaIO/ImageMagick.jl#49]
certain 16-bit TIFF files are using `UFixed8` when read by `Images`.  but not all.  don't have time to debug this now.  filing an issue so i don't forget.

**Comment by bjarthur** [comment]
i should add that this happens on both julia 0.4 and 0.5.  `QuartzImageIO` on os x does not have a problem with the same files.  neither does ImageJ.

**Comment by timholy** [comment]
Interesting that it's some but not all. Thanks for filing the issue.
