### ISSUE TITLE
homebrew imagemagick updated to 7.0.4

### ISSUE THREAD

**Issue by bjarthur** [JuliaIO/ImageMagick.jl#57]
i think this update just happened last night.  IIRC there are API changes in imagemagick 7 that would require substantial changes to imagemagick.jl to support.  if true, it seems in the short term we should perhaps modify the build script, again, to have homebrew install the last 6.9 imagemagick version instead.  anyone know how to do this?

**Comment by bjarthur** [comment]
i've found a private tap for imagemagick 6.9.7:

```
brew install crazymykl/homebrew-custom/imagemagick@6
```

as discussed [here](http://discourse.brew.sh/t/imagemagick-7-x-php56-imagick-breaking-change/589/2) and [here](https://github.com/Homebrew/homebrew-core/pull/8756).

checking out master of ImageMagick.jl, editing line 94 of deps/build.jl to use "imagemagick@6", then building and testing...  it all works.

but i wonder whether we should host our own formula in `staticfloat/homebrew-juliadeps`.

**Comment by ilovezfs** [comment]
@bjarthur Just a heads up that we've now merged ImageMagick 6 as "imagemagick@6"
