### ISSUE TITLE
could not spawn `'C:\Program Files\ImageMagick-6.9.8-Q16-HDRI\convert.exe C:\Windows\System32\convert.exe'

### ISSUE THREAD

**Issue by salsaif** [JuliaIO/ImageMagick.jl#88]
Had this error while running this script:
```frames = Frames(MIME("image/png"), fps=10)
for frame in 1 : length(sim.states)
     s = render(sim.states[frame], sim.roadway, cam=FitToContentCamera(), car_colors=carcolors)
    push!(frames, s)
end
println("creating gif...")
write("gif.gif", frames)
```
could not spawn `'C:\Program Files\ImageMagick-6.9.8-Q16-HDRI\convert.exe
C:\Windows\System32\convert.exe' 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\1.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\2.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\3.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\4.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\5.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\6.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\7.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\8.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\9.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\10.png' -delay 1x10.0 -alpha deactivate 'C:\Users\sauda\AppData\Local\Temp\jl_68BD.tmp\11.png' -delay 1x10.0 -alpha deactivate gif.gif`: no such file or directory (ENOENT)

 in _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::RawFD, ::RawFD, ::RawFD) at .\process.jl:321
 in #414 at .\process.jl:478 [inlined]
 in setup_stdio(::Base.##414#415{Cmd,Ptr{Void},Base.Process}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:466
 in #spawn#413(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}, ::Bool, ::Bool) at .\process.jl:477
 in run at .\process.jl:591 [inlined]
 in #write#4(::Float64, ::Function, ::String, ::Reel.Frames{MIME{Symbol("image/png")}}) at C:\Users\sauda\.julia\v0.5\Reel\src\Reel.jl:80
 in write(::String, ::Reel.Frames{MIME{Symbol("image/png")}}) at C:\Users\sauda\.julia\v0.5\Reel\src\Reel.jl:63

Any insight on how to resolve this?

**Comment by musm** [comment]
Looks like it's picking up the wrong convert?

what does  your deps/deps.jl say? in `Pkg.dir("ImageMagick");`

**Comment by salsaif** [comment]
This is what I get from `Pkg.dir("ImageMagick")`:
"C:\\Users\\sauda\\.julia\\v0.5\\ImageMagick"

**Comment by musm** [comment]
I mean the file called `deps.jl` within that folder

**Comment by salsaif** [comment]
```# This is an auto-generated file; do not edit

# Pre-hooks
function init_deps()
    ENV["MAGICK_CONFIGURE_PATH"]    = "C:\\Users\\sauda\\.julia\\v0.5\\ImageMagick\\deps\\usr\\lib\\x64"
    ENV["MAGICK_CODER_MODULE_PATH"] = "C:\\Users\\sauda\\.julia\\v0.5\\ImageMagick\\deps\\usr\\lib\\x64"
end
init_deps()

# Macro to load a library
macro checked_lib(libname, path)
    ((VERSION >= v"0.4.0-dev+3844" ? Base.Libdl.dlopen_e : Base.dlopen_e)(path) == C_NULL) && error("Unable to load \n\n$libname ($path)\n\nPlease re-run Pkg.build(package), and restart Julia.")
    quote const $(esc(libname)) = $path end
end

# Load dependencies
@checked_lib libwand "C:\\Users\\sauda\\.julia\\v0.5\\ImageMagick\\deps\\usr\\lib\\x64\\CORE_RL_wand_.DLL"

# Load-hooks

```

**Comment by musm** [comment]
btw can you please try and delete *everything* in that folder *except*  `build.jl`  and then start julia and do `Pkg.build("ImageMagick")` and report back?

**Comment by salsaif** [comment]
Same error

**Comment by musm** [comment]
so doing Pkg.build results in *no* errors?

what happens when you do
```
using ImageMagick
Pkg.test("ImageMagick")
```

can you copy ane paste the result
its hard to see what's triggering the error from you stacktrace in the post

**Comment by salsaif** [comment]
Pkg.build ran fine.

Pkg.test returned this:
```
INFO: Computing test dependencies for ImageMagick...
INFO: Cloning cache of ZipFile from https://github.com/fhs/ZipFile.jl.git
INFO: Installing ZipFile v0.3.0
INFO: Testing ImageMagick
=============================[ ERROR: ImageMagick ]=============================

failed process: Process(`'C:\Users\sauda\AppData\Local\Julia-0.5.0\bin\julia' -Cx86-64 '-JC:\Users\sauda\AppData\Local\Julia-0.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\sauda\.julia\v0.5\ImageMagick\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: Removing ZipFile v0.3.0
ImageMagick had test errors

 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
```

**Comment by musm** [comment]
Well basically it's picking up the `convert` function in C:\Windows instead of the one downloaded by BinDeps. Now why this is happening makes no sense.  As a note I too am on Windows but can't seem to replicate the issue.

**Comment by musm** [comment]
fixed by https://github.com/JuliaIO/ImageMagick.jl/pull/93
